name: flutter_news_app
description: "A Flutter News App By Shubham Bane."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #################icons & fonts###############
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  #################state management#################
  flutter_bloc: ^8.1.3

  #################comparing dart objects#################
  equatable: ^2.0.5

  #################service locator#################
  get_it: ^7.6.4

  #################dateFormat#################
  intl: ^0.19.0

  #################Database#################
  floor: ^1.4.2

  #################make request to api#################
  retrofit: ^4.0.3

  #################Hooks#################
  flutter_hooks: ^0.20.3

  #################chached image #################
  cached_network_image: ^3.3.0
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.5
  floor_generator: ^1.4.2
  build_runner: ^2.4.7

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
